# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 375c0dbd899ed44123dd344bde150e9a1aca9f369bbd98382c152aebf4bdf025294c2a9ccb585fe004f1c1bfd44164827b1b721e845c151ba765ce3ec3086b9a

test:
  secret_key_base: fe5edd90a6ebcec15c989b6336c9622a28f8f4c695ab4f984cdbc10e26caf3723b86da7a1af3633450b75afb1f7cbbdc2e5bbb47fead20377a9597b9ef5a9cdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
